# Generated by Django 6.0.6 on 2026-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('genre', models.CharField(max_length=100, verbose_name='Gênero')),
                ('developer', models.CharField(max_length=150, verbose_name='Desenvolvedora')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
